# Generated by Django 3.1 on 2021-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='isMayorEdad',
            field=models.BooleanField(default=False),
        ),
    ]
